//-------------------- Color ---------------------

//-------- Design --------
#define Border_Color 8
#define TitleMenu_Color 8
#define BoxMenu_Color 8
#define MainMenu_Color 8
#define TitleGameOver_Color 12
#define BorderGameOver_Color 8
#define BorderWinner_Color 8
#define TitleWinner_Color 10
#define BorderRecords_Color 8
#define TextRecords_Color 8
#define Easy_Color 10
#define Normal_Color 14
#define Hard_Color 12
#define BorderHowToPlay_Color 8
#define TextHowToPlay_Color 8
#define GameScreen_Color 8
#define Default_Color 7
//-------- Object --------
#define Player_Color 15
#define Enemy_Color 13
#define DeadEnemy_Color 5
#define DWall_Color 14
#define DestroyedWall_Color 6
#define InDWall_Color 12
#define TNT_Color 76
#define EndBlock_Color 10
#define TextBack_Color 15
#define White_Color 15
