//------------------ Parameters ------------------

//--------- Easy ---------
#define Xe 17
#define Ye 7
#define EndGameXe Xe+42
#define EndGameYe Ye+12
#define NumberBoxEasy 10
#define NumberEnemyEasy 4
//-------- Normal --------
#define Xsm 38
#define Ysm 5
#define Xm 10
#define Ym 5
#define EndGameXm Xm+28
#define EndGameYm Ym+16
#define NumberBoxNormal 15
#define NumberEnemyNormal 6
//--------- Hard ---------
#define Xsh 38
#define Ysh 13
#define Xh 3
#define Yh 3
#define EndGameXh Xh+35
#define EndGameYh Yh+20
#define NumberBoxHard 15
#define NumberEnemyHard 6
